name = "BEAST"
uuid = "bb4162c7-ba94-5a20-af32-d8ec4428bdd1"
version = "2.7.0"

[deps]
AbstractTrees = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"
BlockArrays = "8e7c35d0-a365-5155-bbbb-fb81a777f24e"
CollisionDetection = "2b5bf9a6-f3f8-5352-af9c-82bb4af718d8"
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
CompScienceMeshes = "3e66a162-7b8c-5da0-b8f8-124ecd2c3ae1"
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"
ConvolutionOperators = "15927181-a1bb-497c-b745-8dbf505c019d"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
ExtendableSparse = "95c220a8-a1cf-11e9-0c77-dbfce5f500b3"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
FastGaussQuadrature = "442a2c76-b920-505d-bb47-c5924d526838"
FillArrays = "1a297f60-69ca-5386-bcde-b61e274b549b"
Infiltrator = "5903a43b-9cc3-4c30-8d17-598619ec4e9b"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
IterativeSolvers = "42fd0dbc-a981-5370-80f2-aaf504508153"
LiftedMaps = "d22a30c1-52ac-4762-a8c9-5838452405e0"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LinearMaps = "7a12625a-238d-50fd-b39a-03d52299707e"
NestedUnitRanges = "032820ab-dc03-4b49-91f4-7d58d4da98b3"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
SauterSchwab3D = "0a13313b-1c00-422e-8263-562364ed9544"
SauterSchwabQuadrature = "535c7bfe-2023-5c1d-b712-654ef9d93a38"
SharedArrays = "1a1011a3-84de-559e-8e89-a11a2f7dc383"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
TestItems = "1c621080-faea-4a02-84b6-bbd5e436b8fe"
WiltonInts84 = "a3e2863e-c0ee-5ff6-a523-307a4cdc8724"

[compat]
AbstractTrees = "0.4.4"
BlockArrays = "0.10, 0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 1"
CollisionDetection = "0.1.7"
Combinatorics = "0.7, 1"
CompScienceMeshes = "0.9.4"
Compat = "2, 3, 4"
ConvolutionOperators = "0.4"
ExtendableSparse = "1.4"
FFTW = "0.2.3, 1"
FastGaussQuadrature = "0.3, 0.4, 0.5, 1"
FillArrays = "0.11, 0.12, 0.13, 1"
Infiltrator = "1.8.2"
IterativeSolvers = "0.9"
LiftedMaps = "0.5.1"
LinearMaps = "3.7 - 3.9, 3.11.2"
NestedUnitRanges = "0.2"
Requires = "1"
SauterSchwab3D = "0.2"
SauterSchwabQuadrature = "2.4.0"
SpecialFunctions = "0.7, 0.8, 0.9, 0.10, 1, 2"
StaticArrays = "0.8.3, 0.9, 0.10, 0.11, 0.12, 1"
TestItems = "0.1.1, 1"
WiltonInts84 = "0.2.8"
julia = "1.10"
