name = "BEAST"
uuid = "bb4162c7-ba94-5a20-af32-d8ec4428bdd1"

[deps]
BlockArrays = "8e7c35d0-a365-5155-bbbb-fb81a777f24e"
CollisionDetection = "2b5bf9a6-f3f8-5352-af9c-82bb4af718d8"
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
CompScienceMeshes = "3e66a162-7b8c-5da0-b8f8-124ecd2c3ae1"
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
FastGaussQuadrature = "442a2c76-b920-505d-bb47-c5924d526838"
IterativeSolvers = "42fd0dbc-a981-5370-80f2-aaf504508153"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SauterSchwabQuadrature = "535c7bfe-2023-5c1d-b712-654ef9d93a38"
SharedArrays = "1a1011a3-84de-559e-8e89-a11a2f7dc383"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
WiltonInts84 = "a3e2863e-c0ee-5ff6-a523-307a4cdc8724"

[compat]
CollisionDetection = "^0.1"
Combinatorics = "^0.7"
CompScienceMeshes = "^0.2.5"
Compat = "^2"
FFTW = "^0.2.3, ^1"
FastGaussQuadrature = "^0.3, ^0.4"
IterativeSolvers = "^0.7, ^0.8"
SauterSchwabQuadrature = "^2.1"
SpecialFunctions = "^0.7, ^0.8"
StaticArrays = "^0.8.3, ^0.9, ^0.10, ^0.11, ^0.12"
WiltonInts84 = "^0.2.0"
julia = "^0.7, ~1"

[extras]
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Pkg", "DelimitedFiles", "LinearAlgebra", "SparseArrays", "Test", "Distributed"]
