name = "BEAST"
uuid = "bb4162c7-ba94-5a20-af32-d8ec4428bdd1"
version = "2.2.0"

[deps]
AbstractTrees = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"
BlockArrays = "8e7c35d0-a365-5155-bbbb-fb81a777f24e"
CollisionDetection = "2b5bf9a6-f3f8-5352-af9c-82bb4af718d8"
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
CompScienceMeshes = "3e66a162-7b8c-5da0-b8f8-124ecd2c3ae1"
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"
ConvolutionOperators = "15927181-a1bb-497c-b745-8dbf505c019d"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
FastGaussQuadrature = "442a2c76-b920-505d-bb47-c5924d526838"
FillArrays = "1a297f60-69ca-5386-bcde-b61e274b549b"
GmshTools = "82e2f556-b1bd-5f1a-9576-f93c0da5f0ee"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
IterativeSolvers = "42fd0dbc-a981-5370-80f2-aaf504508153"
Lazy = "50d2b5c4-7a5e-59d5-8109-a42b560f39c0"
LiftedMaps = "d22a30c1-52ac-4762-a8c9-5838452405e0"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LinearMaps = "7a12625a-238d-50fd-b39a-03d52299707e"
NestedUnitRanges = "032820ab-dc03-4b49-91f4-7d58d4da98b3"
Plotly = "58dd65bb-95f3-509e-9936-c39a10fdeae7"
PlotlyBase = "a03496cd-edff-5a9b-9e67-9cda94a718b5"
PlotlyJS = "f0f68f2c-4968-5e81-91da-67840de0976a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
SauterSchwab3D = "0a13313b-1c00-422e-8263-562364ed9544"
SauterSchwabQuadrature = "535c7bfe-2023-5c1d-b712-654ef9d93a38"
SharedArrays = "1a1011a3-84de-559e-8e89-a11a2f7dc383"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
SparseMatrixDicts = "5cb6c4b0-9b79-11e8-24c9-f9621d252589"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
TableView = "40c74d1a-b44c-5b06-a7c1-6cbea58ea978"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
WiltonInts84 = "a3e2863e-c0ee-5ff6-a523-307a4cdc8724"

[compat]
AbstractTrees = "0.4.4"
BlockArrays = "0.10, 0.11, 0.12, 0.13, 0.14, 0.15, 0.16"
CollisionDetection = "0.1.5"
Combinatorics = "0.7, 1"
CompScienceMeshes = "0.6.0"
Compat = "2, 3, 4"
ConvolutionOperators = "0.4"
FFTW = "0.2.3, 1"
FastGaussQuadrature = "0.3, 0.4, 0.5, 1"
FillArrays = "0.11, 0.12, 0.13, 1"
IterativeSolvers = "0.9"
LiftedMaps = "0.5.1"
LinearMaps = "3.7 - 3.9, 3.11.2"
NestedUnitRanges = "0.2"
Requires = "1"
SauterSchwab3D = "0.1"
SauterSchwabQuadrature = "2.3.0"
SparseMatrixDicts = "< 0.2.8"
SpecialFunctions = "0.7, 0.8, 0.9, 0.10, 1, 2"
StaticArrays = "0.8.3, 0.9, 0.10, 0.11, 0.12, 1"
WiltonInts84 = "0.2.5"
julia = "1.6"
