[deps]
BEAST = "bb4162c7-ba94-5a20-af32-d8ec4428bdd1"
CompScienceMeshes = "3e66a162-7b8c-5da0-b8f8-124ecd2c3ae1"
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"
Plotly = "58dd65bb-95f3-509e-9936-c39a10fdeae7"
PlotlyBase = "a03496cd-edff-5a9b-9e67-9cda94a718b5"
PlotlyDocumenter = "9b90f1cd-2639-4507-8b17-2fbe371ceceb"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
