[deps]
BEAST = "bb4162c7-ba94-5a20-af32-d8ec4428bdd1"
CompScienceMeshes = "3e66a162-7b8c-5da0-b8f8-124ecd2c3ae1"
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"
Makeitso = "5616b7aa-48d8-5ba3-83fe-06b58d5edc20"
NestedUnitRanges = "032820ab-dc03-4b49-91f4-7d58d4da98b3"
PlotlyBase = "a03496cd-edff-5a9b-9e67-9cda94a718b5"
PlotlyDocumenter = "9b90f1cd-2639-4507-8b17-2fbe371ceceb"
PlotlyJS = "f0f68f2c-4968-5e81-91da-67840de0976a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
